### ISSUE TITLE
白鹭Linux命令行工具在rc/4.0.1版本中有错误

### ISSUE THREAD

**Issue by Raykid** [egret-labs/egret-core#160]
经查发现，在rc/4.0.0分支下可以正常执行egret info命令，但是切换到rc/4.0.1分之下则会报错，报错信息如下：

/data/software/egret-core/tools/lib/core/globals.js:4
let param = require('./param')
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/data/software/egret-core/tools/Entry.js:36:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**后续查看发现，是2017年1月16日18:28由WanderWang提交的版本首次出现问题，提交版本号是4801352**

**Comment by WanderWang** [comment]
这个问题在4.0.2已经得到了修复
