### ISSUE TITLE
运行示例项目时报错 events.js:160 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by oppos69** [egret-labs/egret-core#230]
我在运行示例项目 使用命令 egret startserver CoreExample之后报错
-------------------------------------------------------------------------------------
您安装的最新引擎版本为 5.0.15
当前项目使用版本为 3.2.5
您可以执行 egret upgrade 命令升级项目
正在编译项目...
扫描项目列表
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files (x86)\Egret\EgretLauncher\resources\app\engine\win\node.exe ENOENT
    at exports._errnoException (util.js:1008:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
我是windows10系统

**Comment by himuil** [comment]
你试试先执行egret clean清理一下项目，然后再看看有没有报错
