### ISSUE TITLE
在工程中使用命令行egret publish导出微信小游戏工程报错

### ISSUE THREAD

**Issue by soyemi** [egret-labs/egret-core#270]
提示找不到`game.js`文件，命令行publish不会自动拷贝`egret-weixin-support-1.1.1\template`中的文件到`xxx_wxgame`目录中。

```cmd
D:\CIS\CatHospital-WeChat\MapDemo\TestMap>egret publish
您正在使用白鹭编译器 5.2.1 版本
Start to publish wxgame version:
{ Error: ENOENT: no such file or directory, open 'D:\CIS\CatHospital-WeChat\MapDemo\TestMap_wxgame\game.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at WxgamePlugin.<anonymous> (D:\CIS\CatHospital-WeChat\MapDemo\TestMap\scripts\wxgame\wxgame.ts:87:36)
    at step (D:\CIS\CatHospital-WeChat\MapDemo\TestMap\scripts\wxgame\wxgame.ts:32:23)
    at Object.next (D:\CIS\CatHospital-WeChat\MapDemo\TestMap\scripts\wxgame\wxgame.ts:13:53)
    at D:\CIS\CatHospital-WeChat\MapDemo\TestMap\scripts\wxgame\wxgame.ts:7:71
    at __awaiter (D:\CIS\CatHospital-WeChat\MapDemo\TestMap\scripts\wxgame\wxgame.ts:3:12)
    at WxgamePlugin.onFinish (D:\CIS\CatHospital-WeChat\MapDemo\TestMap\scripts\wxgame\wxgame.ts:83:16)
    at r.<anonymous> (C:\Users\Yemi\AppData\Roaming\Egret\engine\5.2.1\tools\lib\resourcemanager\index.js:4362:39)
    at r (C:\Users\Yemi\AppData\Roaming\Egret\engine\5.2.1\tools\lib\resourcemanager\index.js:4455:27)
    at Object.next (C:\Users\Yemi\AppData\Roaming\Egret\engine\5.2.1\tools\lib\resourcemanager\index.js:4408:28)
    at C:\Users\Yemi\AppData\Roaming\Egret\engine\5.2.1\tools\lib\resourcemanager\index.js:4403:45
    at s (C:\Users\Yemi\AppData\Roaming\Egret\engine\5.2.1\tools\lib\resourcemanager\index.js:4383:20)
    at r.d [as _flush] (C:\Users\Yemi\AppData\Roaming\Egret\engine\5.2.1\tools\lib\resourcemanager\index.js:4336:24)
    at r.<anonymous> (C:\Users\Yemi\AppData\Roaming\Egret\engine\5.2.1\tools\lib\resourcemanager\index.js:3851:57)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\CIS\\CatHospital-WeChat\\MapDemo\\TestMap_wxgame\\game.js' }
```

**Comment by soyemi** [comment]
已自行解决
